### ISSUE TITLE
Unable to configure users to only see certain dives in a cruise

### ISSUE THREAD

**Issue by jogarcia-whoi** [WHOIGit/ndsf-sealog-server#29]
There are two accounts for viewing cruise AT50-11 on sealog.whoi.edu/sealog-alvin. One should have access to all the dives (user `at50-11`), the other (user `at50-11pgirguis`) should only have access to one of the dives (AL5191).

As admin, using **System Management->Dives->Alvin-D5191->User permissions**, I enabled access for the `at50-11` and `at50-11pgirguis` accounts. **System Management->Cruises->AT50-11** showed the cruise as hidden and **System Management->Cruises->AT50-11->User permissions** showed that only the `at50-11` user was granted access. I logged out, logged back in as `at50-11pgirguis` and could not find AT50-11. I logged in as admin again and granted AT50-11 access for `at50-11pgirguis` as well via **System Management->Cruises->AT50-11->User permissions**. I logged out, logged in as `at50-11pgirguis` and was able to see _all_ the dives from the cruise instead of just AL5191.

I finally tried using **System Management->Users->at50-11pgirguis->Cruise/dive permissions**, setting it like so (I didn't undo any of the prior steps):
![image](https://github.com/WHOIGit/ndsf-sealog-client/assets/87498403/8f7569e0-f0c7-4d8b-b7c7-306cc3d29882)

I logged in as `at50-11pgirguis` again but had no luck; I could still access all the dives in the cruise.

**Comment by rgov** [comment]
Seems like the logic is:

```js
        if (useAccessControl && !request.auth.credentials.scope.includes('admin')) {
          query.$or = [{ lowering_hidden: false }, { lowering_access_list: request.auth.credentials.id }];
        }
```

It doesn't strike me as wrong, though. Are we sure some kind of browser caching isn't happening?

**Comment by jogarcia-whoi** [comment]
Hi, @rgov. Unfortunately, I don't think it's a browser caching issue. I just cleared all browsing data from Chromium on my laptop, relaunched Chromium, and logged in as `at50-11pgirguis`. All dives in AT50-11 are still visible to that user.

**Comment by rgov** [comment]
Can you please provide passwords to these accounts via Slack so we can look at the API responses?

**Comment by jogarcia-whoi** [comment]
> Can you please provide passwords to these accounts via Slack so we can look at the API responses?

Definitely! Doing that now.

**Comment by rgov** [comment]
Please note there is a distinction between a hidden *cruise* and a hidden *dive/lowering*. If a user has access to a dive/lowering, they also have access to all non-hidden lowerings for that cruise. (**Edit:** A previous version of this post had a confusing mistake/typo.)

According to the API response, and to the UI, these dives are NOT hidden:

<img width="521" alt="image" src="https://github.com/WHOIGit/ndsf-sealog-server/assets/108767/55d12c34-f460-479f-848b-c7a9e82bc6f0">

---

Alvin-D5191 access list: `    "lowering_access_list": ["64c2cebd30ba83001aa7ad59", "64c2cebd30ba83001aa7ad59", "64cd079b30ba83001aa7ad5a", "64cd079b30ba83001aa7ad5a"],`

Alvin-D5190 access list: `    "lowering_access_list": ["64c2cebd30ba83001aa7ad59", "64c2cebd30ba83001aa7ad59"],`

Noting that the entries here are duplicated, which is strange.

* **64c2cebd30ba83001aa7ad59**: user `at50-11`
* **64cd079b30ba83001aa7ad5a**: user `at50-11pgirguis`

If Alvin-5190 were hidden, it should not be visible to user `at50-11pgirguis`.

**Comment by rgov** [comment]
If you want a change to the behavior here, for example to auto-hide lowerings when a cruise is hidden, please file an enhancement request.
